name = "boringan"
type = "javascript"
compatibility_date = "2025-04-02"

[site]
bucket = "./.output/public"
entry-point = "./.output/server"

[[routes]]
  pattern = "https://www.boringan.com/*"
  custom = "my-worker"
