name = "boringan"
type = "javascript"
compatibility_date = "2025-04-02"

[site]
bucket = "./.output/public"
entry-point = "./.output/server"

[[routes]]
  pattern = "https://www.boringan.com/*"
  custom = "my-worker"

[[ d1_databases ]]
binding = "DB"
database_name = "db_boringan"
database_id = "54f325df-c95d-4282-9528-700763995921"
